# Generated by Django 3.1.2 on 2020-10-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201022_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_ip',
            new_name='user',
        ),
    ]
