# Generated by Django 3.1.2 on 2020-10-22 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201022_0754'),
        ('blog', '0007_auto_20200517_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='blog/post'),
        ),
        migrations.AddField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(related_name='blog_like', to='account.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_or_not',
            field=models.BooleanField(default=False),
        ),
    ]
