# Generated by Django 3.1.2 on 2020-10-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201022_0754'),
        ('blog', '0008_auto_20201022_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='blog_like', to='account.User'),
        ),
    ]
