# Generated by Django 3.1.2 on 2020-10-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201022_1936'),
        ('blog', '0010_auto_20201022_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_likes', to='account.User'),
        ),
    ]
