# Generated by Django 3.1.2 on 2020-10-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201022_1936'),
        ('blog', '0012_auto_20201025_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_likes', to='account.User'),
        ),
    ]
