# Generated by Django 3.1.2 on 2020-10-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgurl',
            field=models.TextField(blank=True, max_length=2083),
        ),
    ]
