# Generated by Django 3.1.2 on 2020-10-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201026_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imgurl',
        ),
    ]
