# Generated by Django 3.1.2 on 2020-10-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20201027_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog/post/category'),
        ),
    ]
