# Generated by Django 3.1.2 on 2020-10-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_subcategory_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='blog/post'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='blog/post'),
        ),
    ]
