# Generated by Django 3.1.2 on 2020-10-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20201028_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='subcategory', max_length=255),
        ),
    ]
