# Generated by Django 3.1.2 on 2020-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date',
            field=models.CharField(default='14 November 2020', max_length=255),
        ),
    ]
