# Generated by Django 3.1.2 on 2020-11-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20201109_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.BooleanField(default=False),
        ),
    ]
