# Generated by Django 3.1.2 on 2020-11-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_post_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pdf',
        ),
    ]
