# Generated by Django 3.1.2 on 2020-11-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_remove_post_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.BooleanField(default=False),
        ),
    ]
