# Generated by Django 3.1.2 on 2020-11-10 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_post_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video_or_not',
            new_name='video',
        ),
    ]
