# Generated by Django 3.1.2 on 2020-11-11 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20201110_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='post/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='blog/post/subcat'),
        ),
    ]
