# Generated by Django 3.1.2 on 2020-11-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20201111_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='blog/post1'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='blog/thumbnail'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='blog/subcat'),
        ),
    ]
