# Generated by Django 3.1.2 on 2020-11-12 15:08

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_auto_20201112_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=None),
        ),
    ]
