# Generated by Django 3.1.2 on 2020-11-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20201112_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='pdf_file_extra',
            field=models.FileField(blank=True, null=True, upload_to='blog/post2'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Any Title', max_length=120),
        ),
    ]
