# Generated by Django 3.1.2 on 2020-11-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_auto_20201113_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='student',
            field=models.CharField(default='Student Name', max_length=120),
        ),
    ]
